### PR TITLE
Improve off-canvas navigation

### PR DESCRIPTION
**Pull request by hypeJunction**
Improves off-canvas consitency and responsivenes.
Makes topbar icons and text less jumpy, makes colors consistent

### CODE REVIEW

**Comment by hypeJunction** [comment]
Just freestyled some improvements. I am really bothered by things that don't align, they distract me from my tasks.

**Comment by michelesbw** [comment]
Unfortunately not being a dev I can't say anything if I don't actualy see the changes but if Juho and Luca agree of course it is ok for me :)

**Comment by juho-jaakkola** [comment]
@michelesbw I've installed this to https://beta.socialbusinessworld.org so you can test.

**Comment by juho-jaakkola** [comment]
- I kind of liked it when the same icon was used both for opening and closing the site menu. What's the motivation to have a separate icon for closing it?
 - It looks a bit silly on narrow viewport, how site menu pushes topbar from it's way

**Comment by hypeJunction** [comment]
> I kind of liked it when the same icon was used both for opening and closing the site menu. What's the motivation to have a separate icon for closing it?

I have read a few articles on UX that suggests changing them. It can be < instead of an x.

> It looks a bit silly on narrow viewport, how site menu pushes topbar from it's way

We remove an animation. The motivation is to keep the menu full width and scrollable.

**Comment by juho-jaakkola** [comment]
> I have read a few articles on UX that suggests changing them. It can be < instead of an x.

Ok, the idea sounds good to me. On desktop it seemed weird, but works fine on mobile.

**Comment by michelesbw** [comment]
Knowing average user the X would be also perceived as "close everything" (especially on mobiles) so maybe the < would be better imho and, if possible, in mobile not taking the full width but keeping ie. 75% for the main menu animation would help see that the rest of the site is still there :)

**Comment by hypeJunction** [comment]
@juho-jaakkola I have added a bunch of stuff here. Could you deploy so that everyone can see?

**Comment by juho-jaakkola** [comment]
Deployed to beta.

**Comment by michelesbw** [comment]
Menu items below Translation editor are not visualized and when closing main menu, the transition effect is not nice for eyes, it almost flashes.

**Comment by hypeJunction** [comment]
I will replace with jQuery transitions. CSS transitions can be weird at times.

**Comment by michelesbw** [comment]
Thanks! I think current theme on production has the solution for this and also for fitting sidebar there (possibly after main menu not before as it is now)

**Comment by hypeJunction** [comment]
It's unfortunate that in the abundance of the changes, you only see a flashy menu item...

**Comment by michelesbw** [comment]
Heeeey don't be so sensitive. It's the first things I noticed and I reported them :)
I'm very out of time...that's all.
"Menu items below Translation editor are not visualized" not a small thing and actually I love the faded main page when opening the menu, the "<" instead of X ...never take me wrong man! :)

**Comment by michelesbw** [comment]
Also, let's see, very basic: "improve" is not an objective concept especially when it comes to themeing (unfortunately).
Ie. imVho (actually we are 2 people here seeing it and not influencing each other) /activity and /profile/xxx pages don't look very nice but of course we could may be wrong. Width is too high.
Also, wIdgets look the same, what do you mean by "restyle widgets"?
What does "Clean up item listing views" mean?
What does "Restyle discussions mean"?
What does "Better form reset" mean?

Sorry but Juho (and he was right) taught me to be more clear on issues' descriptions and titles, I ask you to do the same because another problem I have is that I can't understand things until I actually see them AND compare to the previous version, which means screenshots before/after OR having a betafordummies.* setup for me and other friends helping out.
Cheers

**Comment by hypeJunction** [comment]
Achieving responsiveness is a difficult task, especially when there is no consistency across list/item/page/layout display. I have strong opinions about things, but those are based on years of experience, so sometimes you will need to trust me on a bigger picture, rather than focusing on little details.

I will add better descriptions and before/after shots.

**Comment by hypeJunction** [comment]
Aren't you able to scroll the long sidebar menu? I am not sure what I can do to make it fit into the screen, there will have be scrolling involved.

**Comment by michelesbw** [comment]
Sorry but I don't agree on few points:
1 - never said anything is easy = I know responsiveness is difficult;
2 - "no consistency" is not equal to little/less consistency;
3 - I also have strong opinions based on 10+ years of users' "complaints"...(wordpress, elgg, prestashop, cubecart, custom cms,...) but I still have a lot to learn from users and everybody;
4 - I trust you by default but can not (should I?) avoid saying what I think;
5 - points above and my previous comment are not "small details" at all (ie. can't scroll the whole main menu);
6 - at the end themeing is also about personal preferences and tastes...what shouldn't be personal is taking comments as mere criticism.

> Aren't you able to scroll the long sidebar menu? I am not sure what I can do to make it fit into the screen, there will have be scrolling involved.

What I'm not able to scroll is the main menu, below Translation editor are other options, not viewable, not clickable.

As for sidebar please see prod site's groups/all page (from mobile) to get what I mean.

Cheers

**Comment by hypeJunction** [comment]
I am going to fork the theme and build it in a way I think is right. You can then decide whether you want to use it.

**Pull request closed without merging**
