### PR TITLE
feat(lists): integrates comments and discussions with sortable list interface

### PR DESCRIPTION
**Pull request by hypeJunction**
Comments and discussion replies are now displayed with filters when hypeLists 4.1.0 is active.

### CODE REVIEW

**Comment by hypeJunction** [comment]
Not sure if we want this in the theme, or if I should create a separate plugin. 
@michelesbw What other lists will you need integrated? Perhaps we could move them all into a separate plugin.

**Comment by michelesbw** [comment]
Our users asked for (and partially funded) Sorting and filtering entities and comments/replies possibly by saving preferences in users' settings.
So, discussions, comments and replies for sure and what possible as for a consistent UX (otherwise they get confused among site's areas). What do you think?

**Comment by hypeJunction** [comment]
Ok  I will need to add discussions and global personal preferences. I think I will move these out into a separate plugin.

**Comment by michelesbw** [comment]
But on Beta we already have it on discussions if I am not wrong, am I?

**Comment by hypeJunction** [comment]
Did you add the group_discussion plugin? If so, then I don't need to add it.

**Comment by michelesbw** [comment]
Yes I did but now not there anymore after a composer upgrade...but I'll remind Juho about it (it was my own test). Does that also work on discussions outside groups (new in Elgg 2)?

**Comment by hypeJunction** [comment]
No, discussions stay in groups.

**Comment by hypeJunction** [comment]
I moved everything here: https://github.com/sbwtech/sbw_sort
You don't need group_discussion plugin anymore.

**Pull request closed without merging**
